### ISSUE TITLE
analysis_dir does not get created as a new directory

### ISSUE THREAD

**Issue by tanmoy7989** [salilab/PMI_analysis#3]
lines like  (line 1317) fig.savefig(self.analysis_dir+file_out) and others just add the analysis_dir as a filename prefix to the output files so that the intended purpose i.e., have all the analysis output in a separate <analysis_dir> directory is not carried out.

**Comment by benmwebb** [comment]
Right, this is a common (anti)pattern in the lab. It assumes that `analysis_dir` has a trailing `/`. The correct fix here is to use `os.path.join`.
